#!/bin/sh
# save_config - A shell script to save environnement variables file

save_config () {

  for var in $(cat $GENERATOR_CONFIG_FILE | cut -d= -f1) 
  do 
    set | grep $var | sed -e '/var/d' >> "$GENERATOR_CONFIG_FILE.tmp"
  done

  sort -u "$GENERATOR_CONFIG_FILE.tmp" > $GENERATOR_CONFIG_FILE
  rm "$GENERATOR_CONFIG_FILE.tmp"
  dialog --msgbox "Configurations sauvegardés" 8 30 

  
}

